### PR TITLE
fix rpath pysander

### PR DESCRIPTION
**Pull request by hainm**
seems work for me. Not widely tested.

### CODE REVIEW

**Comment by swails** [comment]
YOu still need libgfortran.dylib.  That's why I gave up on OS X -- I didn't feel like figuring out that dependency.

**Comment by hainm** [comment]
that's true. This is why I open an issue here: https://github.com/Amber-MD/conda-recipes/issues/7

to remind anyone who is interested in dealing with osx. :D

**Comment by hainm** [comment]
alternatively, we can learn from [auditwheel[(https://github.com/pypa/auditwheel) (for Linux). It just copied all needed libs. I use it for building pytraj wheel and things are fine.

**Comment by hainm** [comment]
@swails 

I think I just have a dirty fix for it (code is ugly but it works).

Try `conda install pysander -c hainm` (only tried with py35)

I tested on travis and works fine: https://travis-ci.org/hainm/TestPytraj/builds/125310437

What I did is

- make $PREFIX/lib/libsander folder
- find all dependences of libsander (DEPS)
- for each dependence in DEPS that is not in standard /usr/lib dir: change its "id" to "@rpath/libsander/{its_name" (using install_name_tool)
- did the same thing for libsander and pysander*so
- copied all dependences to $PREFIX/lib/libsander

all files

```bash
lib/libsander (fix_rpath_sander) $ ls
libgcc_s.1.dylib    libgfortran.3.dylib libquadmath.0.dylib libsander.dylib     libsanderles.dylib  libstdc++.6.dylib
```

output example from otool
```
$ otool -L libgfortran.3.dylib
libgfortran.3.dylib:
	@rpath/libsander/libgfortran.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	@rpath/libsander/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
	@rpath/libsander/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

and so on.

**Comment by hainm** [comment]
just push new update to this PR.

```bash
conda build pysander --py=3.5
```
should be enough.

**Comment by hainm** [comment]
issue: license incompatibility (guessing).

**Comment by swails** [comment]
Does this collide with other packages that provide libgfortran on Macs?  Or are there none that do that?

**Comment by hainm** [comment]
> Does this collide with other packages that provide libgfortran on Macs? Or are there none that do that?

I don't think so. I put all needed deps for libsander in $PREFIX/lib/libsander/ folder
(not $PREFIX/lib/ folder)

**Comment by hainm** [comment]
output on travis on OSX

https://travis-ci.org/hainm/TestPytraj/jobs/125323045

**Comment by swails** [comment]
nice!

**Comment by hainm** [comment]
close since we have conda build for AmberTools now.

Also added some stuff to fix rpath too.

**Comment by hainm** [comment]
@ Hai : do not delete the `fix_rpath_sander` (might need to look at the code the future).

**Pull request closed without merging**
